
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DAY_OF_WEEK: Monday
  
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job0:
    runs-on: ubuntu-latest
    needs: job1
  # This workflow contains a single job called "build"
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: step1
        id: step1
        run: |
          CHANGE_ID=CHG45394
          echo "::set-output name=test::$CHANGE_ID"
          echo $GITHUB_REPOSITORY | cut -d'/' -f1
          echo $GITHUB_REPOSITORY | cut -d'/' -f2
      - name: step2
        id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: [ job0, job1 ]
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
